### ISSUE TITLE
Add "Participating Groups" page

### ISSUE THREAD

**Issue by PatrickHeneise** [cyprus-developer-community/cdc.cy#11]
There should be a listing/index page with all participating groups and little bit information about them.

**Comment by MarioSimou** [comment]
Can you assign this issue to me? I will start working on this; I assume the page will be under `/groups`, right? Can you also provide the description of each group or tell me where I can find it?. I will put it [here](https://github.com/cyprus-developer-community/cdc.cy/blob/main/app/routes/index.jsx#L10)

**Comment by PatrickHeneise** [comment]
Done, but you should also be able to pick issues on the top-right: "Assign yourself"

**Comment by PatrickHeneise** [comment]
If you can figure out how to load everything from a separate `.json`, file, we can move the group definitions there and add more details to each object. We'll have to ask all the collaborators in the channel, as I don't have all the data myself.

**Comment by MarioSimou** [comment]
> Done, but you should also be able to pick issues on the top-right: "Assign yourself"

Yeap I have the  option to assign it to myself now

> If you can figure out how to load everything from a separate `.json`, file, we can move the group definitions there and add more details to each object. We'll have to ask all the collaborators in the channel, as I don't have all the data myself.

Do you mean if we could have a configuration file where we store the group definitions there, as well as other data for other pages? I can do that. I can also create some utilities(selectors) that access the data from the config file as well

**Comment by PatrickHeneise** [comment]
Yeah. Would be nice to have the file in our `home` repo, so it's easily accessible: https://github.com/cyprus-developer-community/home

It's possible to fetch via raw url, so we have some sort of "database". Should be sufficient for now.

**Comment by MarioSimou** [comment]
Okay. I will create something within the cdc.cy repository and move it to the home repository when I feel confident that is stable enough. I don't want to keep raising PRs between two repositories

**Comment by MarioSimou** [comment]
Done [here](https://github.com/cyprus-developer-community/cdc.cy/pull/24)
