### ISSUE TITLE
Error on 87 event

### ISSUE THREAD

**Issue by veksa** [cyprus-developer-community/cdc.cy#245]
https://cdc.cy/events/87

![image](https://github.com/cyprus-developer-community/cdc.cy/assets/6467881/4a1e0ec7-0593-4090-a678-5eb47fc29379)

**Comment by NVerban** [comment]
Looks like issue due to format that date is provided in Github event https://github.com/cyprus-developer-community/events/issues/87 Time format should be like 19:00 and duration 3h
