### ISSUE TITLE
Add tests that verify that the app doesn't fail after a release (smoke tests)

### ISSUE THREAD

**Issue by MarioSimou** [cyprus-developer-community/cdc.cy#69]

**Comment by PatrickHeneise** [comment]
This should be relatively simple with Playwright and a GitHub Action; maybe even scheduled every day, in case a dependency breaks like last time.

As far as I know there's also a lighthouse action to "keep score".

**Comment by MarioSimou** [comment]
Another option is [service.http_checks](https://fly.io/docs/reference/configuration/#services-http_checks) in fly.io. We can simple test that we receive a 200 status code. The benefit of this approach is that fly.io will rollback automatically if the tests fail.

I can see the benefits with both approaches. fly.io testing will track issues during deployment, while playwright will make sure that the page is stable after releasing
